### ISSUE TITLE
1.0 release is broken

### ISSUE THREAD

**Issue by Xunnamius** [alvinometric/remark-remove-comments#5]
Thank you for this package. Encountering a problem with the 1.0 release though: the `transformer.js` file seems to be missing from the published package. I fixed it by copy-pasting the file from this repo directly into the package directory under `node_modules`, but that'll only last as long as I don't reinstall my project's dependencies.

I've submitted a fix: #4

**Comment by alvinometric** [comment]
The fix is live in [v1.0.1](https://github.com/alvinometric/remark-remove-comments/releases/tag/v1.0.1)
